title: FE11 7팀
description: GitHub Pages와 Just the Docs를 이용한 팀 협업 공간
markdown: kramdown

# Remote theme 설정
remote_theme: pmarsceill/just-the-docs

# Plugins 설정
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Just the Docs 설정
just_the_docs:
  # Navigation 설정
  navigation:
    - text: "홈"
      url: "/"
    - text: "팀 소개"
      url: "/docs/team/"
    - text: "문서"
      children:
        - text: "시작하기"
          url: "/docs/getting-started/"
        - text: "회의록"
          children:
            - text: "회의록 1"
              url: "/docs/minutes/24-12-19/"
            - text: "회의록 2"
              url: "/docs/minutes/24-12-20/"
  
  # 검색 설정
  search:
    enabled: true
    provider: "local"

# 기타 설정 (필요에 따라 추가)
# 예: favicon, 로고 등
