title: FE11 7팀
description: GitHub Pages와 Just the Docs를 이용한 팀 협업 공간
markdown: kramdown

# Remote theme 설정
remote_theme: pmarsceill/just-the-docs

# Plugins 설정
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs 설정
just_the_docs:
  
  # 검색 설정
  search:
    enabled: true
    provider: "local"

# 기타 설정 (필요에 따라 추가)
# 예: favicon, 로고 등
